on:
  push:
    branches:
      - users/mitokic/gh-action-update

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        id: install-r
        with:
          r-version: '4.1.1'
          use-public-rspm: true


      # - name: Install system dependencies
      #   if: runner.os == 'Linux'
      #   run: |
      #     pak::local_system_requirements(execute = TRUE)
      #     pak::pkg_system_requirements("pkgdown", execute = TRUE)
      #   shell: Rscript {0}

      - name: Install dependencies
        run: |
          install.packages('remotes')
          install.packages('stringi')
          remotes::install_github("https://github.com/microsoft/finnts")
          install.packages('pkgdown')
          
        shell: Rscript {0}

      # - name: Install package
      #   run: R CMD INSTALL .

      - name: Build and deploy pkgdown site
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, branch = "gh-pages2", github_pages = TRUE)'